### ISSUE TITLE
run

### ISSUE THREAD

**Issue by neeraj1164** [lasercata/KRIS#1]
can u plz guid me your project and how to run it.........contect on wtsapp 7892283823

**Comment by lasercata** [comment]
Hello,
As described in the [README](https://github.com/lasercata/KRIS/blob/main/README.md) file, you can download the project from the latest [release](https://github.com/lasercata/KRIS/releases) (actually the v2.0.3), or clone the repo (`git clone https://github.com/lasercata/KRIS.git`).
- If you downloaded the latest release, you then need to unzip the zip file (`unzip KRIS_v*_build_*.zip`), and you can run the file `KRIS_gui.exe` on Windows or `KRIS_gui` on Linux ;
- Else, you have to get [Python3](https://www.python.org/downloads/) and [PyQt5](https://pypi.org/project/PyQt5/) for your system, and then you can run the file `KRIS_gui.py`.

I hope that it is useful.
